// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopsUI.Database;

namespace ShopsUI.Migrations
{
    [DbContext(typeof(ShopsDbContext))]
    [Migration("20210305074453_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ShopsUI.Database.Models.ItemShopModel", b =>
                {
                    b.Property<int>("ItemShopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal?>("BuyPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("SellPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("ItemShopId");

                    b.ToTable("ShopsUI_ItemShops");
                });

            modelBuilder.Entity("ShopsUI.Database.Models.VehicleShopModel", b =>
                {
                    b.Property<int>("VehicleShopId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<decimal>("BuyPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<decimal?>("SellPrice")
                        .HasColumnType("decimal(18, 2)");

                    b.HasKey("VehicleShopId");

                    b.ToTable("ShopsUI_VehicleShops");
                });
#pragma warning restore 612, 618
        }
    }
}
