// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ShopsUI.Database;

namespace ShopsUI.Migrations
{
    [DbContext(typeof(ShopsDbContext))]
    partial class ShopsDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.16")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("ShopsUI.Database.Models.ItemCategoryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("ShopsUI_ItemCategories");
                });

            modelBuilder.Entity("ShopsUI.Database.Models.ItemGroupModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("IsWhitelist")
                        .HasColumnType("tinyint(1)");

                    b.Property<ushort>("ItemShopId")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort>("ItemShopItemId")
                        .HasColumnType("smallint unsigned");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.HasIndex("ItemShopId");

                    b.ToTable("ShopsUI_ItemGroups");
                });

            modelBuilder.Entity("ShopsUI.Database.Models.ItemShopCategoryModel", b =>
                {
                    b.Property<int>("ItemCategoryId")
                        .HasColumnType("int");

                    b.Property<ushort>("ItemShopId")
                        .HasColumnType("smallint unsigned");

                    b.HasKey("ItemCategoryId", "ItemShopId");

                    b.HasIndex("ItemShopId");

                    b.ToTable("ShopsUI_ItemShopCategories");
                });

            modelBuilder.Entity("ShopsUI.Database.Models.ItemShopModel", b =>
                {
                    b.Property<ushort>("Id")
                        .HasColumnType("smallint unsigned");

                    b.Property<decimal?>("BuyPrice")
                        .HasColumnType("decimal(24,2)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<decimal?>("SellPrice")
                        .HasColumnType("decimal(24,2)");

                    b.HasKey("Id");

                    b.ToTable("ShopsUI_ItemShops");
                });

            modelBuilder.Entity("ShopsUI.Database.Models.VehicleCategoryModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.HasKey("Id");

                    b.ToTable("ShopsUI_VehicleCategories");
                });

            modelBuilder.Entity("ShopsUI.Database.Models.VehicleGroupModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("IsWhitelist")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Permission")
                        .IsRequired()
                        .HasColumnType("longtext CHARACTER SET utf8mb4");

                    b.Property<ushort>("VehicleShopId")
                        .HasColumnType("smallint unsigned");

                    b.Property<ushort>("VehicleShopVehicleId")
                        .HasColumnType("smallint unsigned");

                    b.HasKey("Id");

                    b.HasIndex("VehicleShopId");

                    b.ToTable("ShopsUI_VehicleGroups");
                });

            modelBuilder.Entity("ShopsUI.Database.Models.VehicleShopCategoryModel", b =>
                {
                    b.Property<int>("VehicleCategoryId")
                        .HasColumnType("int");

                    b.Property<ushort>("VehicleShopId")
                        .HasColumnType("smallint unsigned");

                    b.HasKey("VehicleCategoryId", "VehicleShopId");

                    b.HasIndex("VehicleShopId");

                    b.ToTable("ShopsUI_VehicleShopCategories");
                });

            modelBuilder.Entity("ShopsUI.Database.Models.VehicleShopModel", b =>
                {
                    b.Property<ushort>("Id")
                        .HasColumnType("smallint unsigned");

                    b.Property<decimal>("BuyPrice")
                        .HasColumnType("decimal(24,2)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("ShopsUI_VehicleShops");
                });

            modelBuilder.Entity("ShopsUI.Database.Models.ItemGroupModel", b =>
                {
                    b.HasOne("ShopsUI.Database.Models.ItemShopModel", "ItemShop")
                        .WithMany("AuthGroups")
                        .HasForeignKey("ItemShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShopsUI.Database.Models.ItemShopCategoryModel", b =>
                {
                    b.HasOne("ShopsUI.Database.Models.ItemCategoryModel", "ItemCategory")
                        .WithMany("ItemShops")
                        .HasForeignKey("ItemCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShopsUI.Database.Models.ItemShopModel", "ItemShop")
                        .WithMany("Categories")
                        .HasForeignKey("ItemShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShopsUI.Database.Models.VehicleGroupModel", b =>
                {
                    b.HasOne("ShopsUI.Database.Models.VehicleShopModel", "VehicleShop")
                        .WithMany("AuthGroups")
                        .HasForeignKey("VehicleShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ShopsUI.Database.Models.VehicleShopCategoryModel", b =>
                {
                    b.HasOne("ShopsUI.Database.Models.VehicleCategoryModel", "VehicleCategory")
                        .WithMany("VehicleShops")
                        .HasForeignKey("VehicleCategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ShopsUI.Database.Models.VehicleShopModel", "VehicleShop")
                        .WithMany("Categories")
                        .HasForeignKey("VehicleShopId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
