database:
  ConnectionStrings:
    default: "Server=127.0.0.1; Database=openmod; Port=3306; User=unturned; Password=password"

shops:
  # Blacklists allow all players to access a given shop
  # unless they have a configured blacklisted permission.
  # When this setting is set to true, shop blacklists will not be ignored.
  blacklistEnabled: false

  # Whitelists allow only the players who have a configured
  # whitelisted permission to access a given shop.
  # When this setting is set to true, shop whitelists will not be ignored.
  whitelistEnabled: false

  defaultCategory:
    items:
      enabled: true
      name: "All"
    vehicles:
      enabled: true
      name: "All"

sellbox: # Default sellbox size. Set either to zero to disable by default.
  width: 8
  height: 6

ui:
  shopsEffect: 29300
  sellBoxEffect: 29400

  logoUrl: "https://i.imgur.com/t6HbFTN.png"

  backgroundsEnabled: true # Sets whether or not the item rarity backgrounds are enabled.

  buttonDelay: 1 # How long to wait until buy/sell buttons can be clicked again in seconds
  categoryButtonDelay: 0.2 # How long to wait until category buttons can be clicked again in seconds.

  showEmptyCategories: false
  showSellOnlyShops: true